#include <stdbool.h>

typedef struct {
	int height;
	int width;

	short* values;
} Map;



// checks if a given point is visible by implementing bresenham's algorithm.
// will walk the line generated by bresenham's until it finds the end point, 
// or it finds a value larger than the starting point. 
bool is_visible(Map map, int x0, int y0, int x1, int y1);
